# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vfd.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'vfd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvfd.proto\x12\x03vfd\"M\n\x0e\x41nalyzeRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\nspeaker_id\x18\x03 \x01(\t\"w\n\x0f\x41nalyzeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x12\n\nrisk_score\x18\x03 \x01(\x02\x12\x0f\n\x07is_fake\x18\x04 \x01(\x08\x12\x1a\n\x12recommended_action\x18\x05 \x01(\t\"3\n\rStreamRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x12\r\n\x05reset\x18\x02 \x01(\x08\"Y\n\x0eStreamResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x0f\n\x07is_fake\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t2\x91\x01\n\x14VoiceForensicService\x12;\n\x0c\x41nalyzeAudio\x12\x13.vfd.AnalyzeRequest\x1a\x14.vfd.AnalyzeResponse\"\x00\x12<\n\x0bStreamAudio\x12\x12.vfd.StreamRequest\x1a\x13.vfd.StreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vfd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=18
  _globals['_ANALYZEREQUEST']._serialized_end=95
  _globals['_ANALYZERESPONSE']._serialized_start=97
  _globals['_ANALYZERESPONSE']._serialized_end=216
  _globals['_STREAMREQUEST']._serialized_start=218
  _globals['_STREAMREQUEST']._serialized_end=269
  _globals['_STREAMRESPONSE']._serialized_start=271
  _globals['_STREAMRESPONSE']._serialized_end=360
  _globals['_VOICEFORENSICSERVICE']._serialized_start=363
  _globals['_VOICEFORENSICSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
