# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vfd_pb2 as vfd__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vfd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceForensicServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAudio = channel.unary_unary(
                '/vfd.VoiceForensicService/AnalyzeAudio',
                request_serializer=vfd__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=vfd__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/vfd.VoiceForensicService/StreamAudio',
                request_serializer=vfd__pb2.StreamRequest.SerializeToString,
                response_deserializer=vfd__pb2.StreamResponse.FromString,
                _registered_method=True)


class VoiceForensicServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeAudio(self, request, context):
        """Unary call for a complete audio file analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """Bidirectional streaming for real-time live call analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceForensicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAudio,
                    request_deserializer=vfd__pb2.AnalyzeRequest.FromString,
                    response_serializer=vfd__pb2.AnalyzeResponse.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=vfd__pb2.StreamRequest.FromString,
                    response_serializer=vfd__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vfd.VoiceForensicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vfd.VoiceForensicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceForensicService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vfd.VoiceForensicService/AnalyzeAudio',
            vfd__pb2.AnalyzeRequest.SerializeToString,
            vfd__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vfd.VoiceForensicService/StreamAudio',
            vfd__pb2.StreamRequest.SerializeToString,
            vfd__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
